export const nameBand = 'PACHELBEL';
export let nameSongs = [
	"CANON EN D MAYOR", /*1*/
	"CANON EN D MAYOR (ORGAN)", /*2*/
	"CHACONNE EN FA MENOR", /*3*/
	"TOCCATA EN E MENOR", /*4*/
	"SIX SHORT PRELUDES", /*5*/
	"WAS GOTT TUT", /*6*/
	"CIACONA EN D", /*7*/
	"FANTASIA ET FUGA", /*8*/
	"DORISCHE TOCCATA", /*9*/
	"PRÄLUDIUM UND FUGE", /*10*/
	"FUGA EN C MAYOR ", /*11*/
	"MAGNIFICAT EN D MAYOR", /*12*/
	"PRELUDIO EN D MENOR", /*13*/
	"RICERCARE EN DO MENOR", /*14*/
	"CHACONNE IN  D MINOR", /*15*/
	"CHACONNE AND 13 VARIATIONS", /*16*/
	"ARIA SEI GEGRÜSSET JESU GÜTIG", /*17*/
	"CIACONA EN RE MENOR ", /*18*/
	"TOCCATA ET FUGA IN D", /*19*/
	"SUITE EN MI MENOR", /*20*/
]